import { useEffect, useState } from 'react'
import { AlertTriangle, CheckCircle2, ShieldAlert, ShieldCheck } from 'lucide-react'
import type { StrategyResult } from '../api/types'
import { useAutoPaper } from '../api/useAutoPaper'
import type { PaperViewState } from './DashboardViews'

const pct=(value:number|null|undefined)=>value==null?'N/A':`${value.toFixed(2)}%`
const num=(value:number|null|undefined,digits=6)=>value==null?'N/A':value.toLocaleString(undefined,{maximumFractionDigits:digits})

function recommendation(result:ReturnType<typeof useAutoPaper>['result']){
 if(!result)return {title:'Belum dievaluasi',body:'Masukkan Stop Loss dan batas risiko, lalu minta TradingGuard mengevaluasi rencana PAPER BUY.',tone:'idle' as const}
 const decision=result.gate?.risk?.decision
 if(result.scheduled&&decision==='ALLOW')return {title:'Transaksi diizinkan',body:'Risk Guard menyetujui proposal. PAPER BUY terukur sudah dijadwalkan dan tetap akan diperiksa ulang pada harga OPEN berikutnya sebelum dieksekusi.',tone:'allow' as const}
 if(decision==='WARNING')return {title:'Sebaiknya tunggu',body:'Risk Guard menemukan kondisi peringatan. TradingGuard tidak menjadwalkan BUY karena hanya keputusan ALLOW yang boleh membuka risiko baru.',tone:'warning' as const}
 return {title:'Jangan beli dulu',body:result.reason||'Syarat keselamatan belum terpenuhi. TradingGuard mempertahankan kondisi fail-closed.',tone:'block' as const}
}

export function AutoPaperControl({paper,strategy,referencePrice}:{paper:PaperViewState;strategy?:StrategyResult;referencePrice?:number}){
 const auto=useAutoPaper()
 const [stop,setStop]=useState(''),[riskBudget,setRiskBudget]=useState('0.5'),[maxAllocation,setMaxAllocation]=useState('20')
 useEffect(()=>{auto.clear()},[strategy?.timestamp]) // eslint-disable-line react-hooks/exhaustive-deps
 const active=Boolean(paper.account?.active),eligible=Boolean(strategy?.data_ready&&(strategy.assessment==='BULLISH'||strategy.assessment==='STRONG_BULLISH'))
 const canEvaluate=active&&eligible&&Boolean(strategy)&&referencePrice!=null&&!auto.running
 const advice=recommendation(auto.result),risk=auto.result?.gate?.risk,sizing=auto.result?.gate?.sizing
 const submit=async()=>{if(!strategy||referencePrice==null)return;const stopValue=Number(stop),riskValue=Number(riskBudget),allocationValue=maxAllocation.trim()===''?null:Number(maxAllocation);if(!Number.isFinite(stopValue)||stopValue<=0||stopValue>=referencePrice){window.alert('Stop Loss harus angka positif dan berada di bawah harga referensi untuk posisi long.');return}if(!Number.isFinite(riskValue)||riskValue<=0){window.alert('Batas risiko harus lebih besar dari 0%.');return}if(allocationValue!==null&&(!Number.isFinite(allocationValue)||allocationValue<=0||allocationValue>100)){window.alert('Batas alokasi harus lebih besar dari 0% dan maksimal 100%.');return}try{await auto.evaluate({strategy,reference_entry_price:referencePrice,stop_loss_price:stopValue,risk_budget_pct:riskValue,max_allocation_pct:allocationValue});await paper.refresh()}catch{/* API error is rendered below */}}
 const tone=advice.tone==='allow'?'border-emerald-500/30 bg-emerald-500/10':advice.tone==='warning'?'border-amber-500/30 bg-amber-500/10':advice.tone==='block'?'border-red-500/30 bg-red-500/10':'border-slate-700 bg-slate-900/50'
 const Icon=advice.tone==='allow'?CheckCircle2:advice.tone==='warning'?AlertTriangle:advice.tone==='block'?ShieldAlert:ShieldCheck
 return <div className="space-y-4">
  <div className="panel rounded-lg p-5"><div className="mono text-[9px] text-slate-500">AUTO-ENTRY PAPER · KEPUTUSAN BACKEND</div><h2 className="mt-1 text-lg font-semibold text-white">Kontrol Risiko Sebelum BUY</h2><p className="mt-2 text-xs leading-5 text-slate-500">Frontend hanya mengirim input. Risk Sizing, RiskContext, Risk Guard, quantity, dan izin transaksi dihitung serta diputuskan oleh backend.</p>
   <div className="mt-5 grid gap-3 md:grid-cols-4"><label className="text-xs text-slate-400">Harga referensi<input readOnly value={referencePrice==null?'N/A':String(referencePrice)} className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white"/></label><label className="text-xs text-slate-400">Stop Loss<input value={stop} onChange={e=>setStop(e.target.value)} inputMode="decimal" placeholder="Di bawah harga entry" className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white"/></label><label className="text-xs text-slate-400">Batas risiko (%)<input value={riskBudget} onChange={e=>setRiskBudget(e.target.value)} inputMode="decimal" className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white"/></label><label className="text-xs text-slate-400">Maks. alokasi (%)<input value={maxAllocation} onChange={e=>setMaxAllocation(e.target.value)} inputMode="decimal" className="mt-1 w-full rounded border border-slate-700 bg-slate-950 px-3 py-2 text-white"/></label></div>
   <div className="mt-4 flex flex-wrap items-center gap-3"><button disabled={!canEvaluate} onClick={()=>void submit()} className="rounded border border-sky-500/30 bg-sky-500/10 px-4 py-2 text-xs font-semibold text-sky-300 disabled:cursor-not-allowed disabled:opacity-40">{auto.running?'Mengevaluasi…':'Evaluasi & Jadwalkan PAPER BUY'}</button><span className="text-[10px] text-slate-500">{!active?'Mulai akun virtual terlebih dahulu.':!eligible?'Kondisi Strategy belum BULLISH/STRONG BULLISH, sehingga BUY belum diizinkan untuk dievaluasi.':'BUY tidak langsung dieksekusi; harga OPEN berikutnya wajib lolos pemeriksaan ulang.'}</span></div>{auto.error&&<div className="mt-4 rounded border border-red-500/30 bg-red-500/10 p-3 text-xs text-red-300">Evaluasi gagal: {auto.error}</div>}
  </div>
  <div className={`rounded-lg border p-5 ${tone}`}><div className="flex items-start gap-3"><Icon className="mt-0.5" size={22}/><div><div className="mono text-[9px] text-slate-500">SARAN TRADINGGUARD</div><div className="mt-1 text-xl font-bold text-white">{advice.title}</div><p className="mt-2 max-w-3xl text-xs leading-6 text-slate-300">{advice.body}</p></div></div>{auto.result&&<div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-4"><div className="panel-soft rounded p-3"><div className="mono text-[9px] text-slate-500">RISK GUARD</div><div className="mt-2 font-semibold text-white">{risk?.decision==='ALLOW'?'DIIZINKAN':risk?.decision==='WARNING'?'PERINGATAN':risk?.decision==='BLOCK'?'DITOLAK':'BELUM TERSEDIA'}</div></div><div className="panel-soft rounded p-3"><div className="mono text-[9px] text-slate-500">RISIKO AKTUAL</div><div className="mt-2 font-semibold text-white">{pct(sizing?.risk_per_trade_pct)}</div></div><div className="panel-soft rounded p-3"><div className="mono text-[9px] text-slate-500">QUANTITY</div><div className="mt-2 font-semibold text-white">{num(sizing?.final_quantity)}</div></div><div className="panel-soft rounded p-3"><div className="mono text-[9px] text-slate-500">ALOKASI</div><div className="mt-2 font-semibold text-white">{pct(sizing?.allocation_pct)}</div></div></div>}{risk&&(risk.block_reasons.length>0||risk.warning_reasons.length>0)&&<div className="mt-4 panel-soft rounded p-4"><div className="mono text-[9px] text-slate-500">ALASAN DARI RISK ENGINE</div><div className="mt-2 space-y-1 text-xs text-slate-300">{[...risk.block_reasons,...risk.warning_reasons].map((reason,index)=><div key={`${reason}-${index}`}>• {reason}</div>)}</div></div>}<div className="mt-4 text-[10px] leading-5 text-slate-500">Status DIIZINKAN bukan jaminan profit. Risiko saat sizing tidak dapat menjamin kerugian maksimum ketika terjadi gap pasar; sebelum eksekusi backend menghitung ulang biaya/slippage dan meminta izin Risk Guard yang baru.</div></div>
 </div>
}
