import { Activity, ShieldAlert } from 'lucide-react'
import { API_BASE_URL, type MarketSource } from '../api/client'
import type { BacktestResult, Candle, IndicatorSnapshot, PaperAccount, PaperPerformanceSnapshot, StrategyResult } from '../api/types'

const NA = 'N/A'
const number = (value: number | null | undefined, digits = 2) => value == null ? NA : value.toFixed(digits)
const money = (value: number | null | undefined) => value == null ? NA : `$${value.toLocaleString(undefined, { maximumFractionDigits: 2 })}`

export type Selection = { source: MarketSource; symbol: string; timeframe: string }
export type PaperViewState = { account: PaperAccount | null; performance: PaperPerformanceSnapshot | null; loading: boolean; available: boolean; message: string | null }
export type BacktestViewState = { result: BacktestResult | null; running: boolean; error: string | null; run: (candles: Candle[], strategies: StrategyResult[]) => Promise<void> }

type MarketDataProps = { selection: Selection; candle?: Candle; indicator?: IndicatorSnapshot; strategy?: StrategyResult; loading: boolean }

function StrategyEvidence({ strategy, loading }: Pick<MarketDataProps, 'strategy' | 'loading'>) {
  if (!strategy?.evidence?.length) return <div className="text-xs text-slate-500">{loading ? 'Loading backend strategy…' : NA}</div>
  return <div className="space-y-3">{strategy.evidence.map((item, index) => <div className="panel-soft rounded p-3 text-xs" key={`${item.indicator}-${index}`}><div className="flex justify-between"><span className="font-semibold text-slate-300">{item.indicator}</span><span className="mono text-sky-400">{item.contribution > 0 ? '+' : ''}{item.contribution}</span></div><div className="mt-1 text-slate-500">{item.description}</div></div>)}</div>
}

export function DashboardView({ selection, candle, indicator, strategy, loading }: MarketDataProps) {
  return <><section className="mb-5 grid gap-4 md:grid-cols-3"><div className="panel rounded-lg p-5"><div className="mono text-[9px] text-slate-500">LATEST MARKET PRICE</div><div className="mt-3 text-3xl font-bold text-white">{money(candle?.close)}</div><div className="mt-2 text-xs text-slate-500">{candle?.symbol ?? selection.symbol} · {candle?.timeframe ?? selection.timeframe}</div><div className="mt-1 mono text-[9px] text-slate-600">{candle ? new Date(candle.timestamp).toLocaleString() : NA}</div></div><div className="panel rounded-lg p-5"><div className="mono text-[9px] text-slate-500">MARKET CONDITION · STRATEGY ENGINE</div><div className="mt-3 text-2xl font-bold text-sky-300">{strategy?.assessment?.replace(/_/g, ' ') ?? NA}</div><div className="mt-2 text-xs text-slate-500">Score {strategy?.score ?? NA} · Normalized {strategy?.normalized_score ?? NA}%</div><div className="mt-4 text-[10px] text-slate-500">Market condition ≠ execution permission.</div></div><div className="panel rounded-lg p-5"><div className="mono text-[9px] text-slate-500">EXECUTION PERMISSION · RISK GUARD</div><div className="mt-3 flex items-center gap-2 text-xl font-bold text-slate-500"><ShieldAlert size={20}/>UNAVAILABLE</div><div className="mt-3 text-xs leading-relaxed text-slate-500">Authoritative RiskContext is incomplete. Entry remains fail-closed.</div></div></section><section className="panel mb-5 rounded-lg p-5"><div className="mb-5 flex items-center justify-between"><div><div className="mono text-[9px] text-slate-500">TECHNICAL ENGINE</div><h2 className="mt-1 font-semibold text-white">EMA · RSI · MACD</h2></div><Activity size={18} className="text-sky-400"/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{[['EMA FAST',indicator?.ema_fast],['EMA SLOW',indicator?.ema_slow],['RSI',indicator?.rsi],['MACD',indicator?.macd],['SIGNAL',indicator?.macd_signal],['HISTOGRAM',indicator?.macd_histogram]].map(([name,value]) => <div className="panel-soft rounded p-3" key={String(name)}><div className="mono text-[9px] text-slate-600">{name}</div><div className="mt-2 font-semibold text-slate-200">{number(value as number | null | undefined, 4)}</div></div>)}</div></section><section className="grid gap-4 lg:grid-cols-2"><div className="panel rounded-lg p-5"><div className="mono mb-4 text-[9px] text-slate-500">STRATEGY EVIDENCE</div><StrategyEvidence strategy={strategy} loading={loading}/></div><div className="panel rounded-lg p-5"><div className="mono text-[9px] text-slate-500">SAFETY BOUNDARY</div><div className="mt-4 space-y-3 text-xs text-slate-400"><p>Real market data is observation input only.</p><p>Frontend does not calculate strategy, risk, accounting, or trade permission.</p><p>Paper Trading is not automatically started or processed.</p><p>No API key, broker credential, or live order execution is used.</p></div></div></section></>
}

export function MarketView({ candles, symbol }: { candles: Candle[]; symbol: string }) {
  const recent = candles.slice(-12).reverse()
  return <div className="panel rounded-lg p-5"><div className="mb-4"><div className="mono text-[9px] text-slate-500">BACKEND MARKET FEED</div><h2 className="text-lg font-semibold text-white">Recent OHLCV · {symbol}</h2></div><div className="overflow-x-auto"><table className="w-full text-left text-xs"><thead className="mono text-[9px] text-slate-500"><tr>{['TIME','OPEN','HIGH','LOW','CLOSE','VOLUME'].map(x => <th className="px-3 py-3" key={x}>{x}</th>)}</tr></thead><tbody>{recent.map(x => <tr className="table-row border-t border-slate-800" key={x.timestamp}><td className="px-3 py-3 text-slate-500">{new Date(x.timestamp).toLocaleString()}</td><td className="px-3 py-3">{number(x.open)}</td><td className="px-3 py-3">{number(x.high)}</td><td className="px-3 py-3">{number(x.low)}</td><td className="px-3 py-3 font-semibold text-white">{number(x.close)}</td><td className="px-3 py-3">{number(x.volume,4)}</td></tr>)}</tbody></table></div></div>
}

export function StrategyView({ strategy, loading }: { strategy?: StrategyResult; loading: boolean }) {
  return <div className="grid gap-4 lg:grid-cols-2"><div className="panel rounded-lg p-5"><div className="mono text-[9px] text-slate-500">BACKEND STRATEGY RESULT</div><div className="mt-4 text-3xl font-bold text-sky-300">{strategy?.assessment?.replace(/_/g,' ') ?? NA}</div><div className="mt-3 text-sm text-slate-400">Score {strategy?.score ?? NA} / 5 · Normalized {strategy?.normalized_score ?? NA}% · Data ready: {strategy ? String(strategy.data_ready) : NA}</div><div className="mt-5 rounded border border-slate-800 p-3 text-xs text-slate-500">This is market-condition scoring, not a buy/sell order and not execution permission.</div></div><div className="panel rounded-lg p-5"><div className="mono mb-4 text-[9px] text-slate-500">EVIDENCE</div><StrategyEvidence strategy={strategy} loading={loading}/></div></div>
}

export function RiskGuardView({ strategy }: { strategy?: StrategyResult }) {
  return <div className="panel rounded-lg p-6"><div className="mono text-[9px] text-slate-500">AUTHORITATIVE RISK GATE</div><div className="mt-4 flex items-center gap-3 text-2xl font-bold text-slate-500"><ShieldAlert/>UNAVAILABLE</div><p className="mt-4 max-w-3xl text-sm leading-6 text-slate-400">V0.7 does not provide every fact required by RiskContext, including authoritative risk-per-trade. TradingGuard therefore refuses to fabricate zero-risk values or reinterpret paper allocation as risk. Prospective entry remains fail-closed.</p><div className="mt-5 panel-soft rounded p-4 text-xs text-slate-500">Market condition: <span className="text-sky-300">{strategy?.assessment?.replace(/_/g,' ') ?? NA}</span> · Execution permission: <span className="font-semibold text-slate-400">UNAVAILABLE</span></div></div>
}

export function PaperTradingView({ paper }: { paper: PaperViewState }) {
  const a = paper.account, p = paper.performance
  return <div className="grid gap-4 lg:grid-cols-2"><div className="panel rounded-lg p-5"><div className="mono text-[9px] text-slate-500">PAPER ACCOUNT · READ ONLY</div><div className="mt-4 text-2xl font-bold text-white">{paper.loading ? 'LOADING…' : paper.available ? 'AVAILABLE' : 'NOT STARTED'}</div><div className="mt-5 grid grid-cols-2 gap-3 text-xs"><div className="panel-soft rounded p-3"><span className="text-slate-500">Cash</span><div className="mt-1 font-semibold">{money(a?.cash)}</div></div><div className="panel-soft rounded p-3"><span className="text-slate-500">Realized equity</span><div className="mt-1 font-semibold">{money(a?.realized_equity)}</div></div><div className="panel-soft rounded p-3"><span className="text-slate-500">Closed trades</span><div className="mt-1 font-semibold">{p?.total_closed_trades ?? NA}</div></div><div className="panel-soft rounded p-3"><span className="text-slate-500">Win rate</span><div className="mt-1 font-semibold">{p ? `${number(p.win_rate_pct)}%` : NA}</div></div></div>{paper.message && <div className="mt-4 text-xs text-amber-300/70">{paper.message}</div>}</div><div className="panel rounded-lg p-5"><div className="mono text-[9px] text-slate-500">POSITION STATE</div><div className="mt-4 text-lg font-semibold text-white">{a?.open_position ? `${a.open_position.symbol} OPEN` : 'NO OPEN POSITION'}</div><div className="mt-4 text-xs leading-6 text-slate-500">Dashboard is read-only. It does not start, reset, or process a paper session automatically. Risk permission remains authoritative.</div></div></div>
}

export function BacktestView({ backtest, candles, strategies, loading }: { backtest: BacktestViewState; candles: Candle[]; strategies: StrategyResult[]; loading: boolean }) {
  return <div className="panel rounded-lg p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="mono text-[9px] text-slate-500">V0.6 BACKTEST ENGINE</div><h2 className="mt-1 text-lg font-semibold text-white">Explicit backend evaluation</h2></div><button disabled={backtest.running || loading || !candles.length} onClick={() => void backtest.run(candles, strategies)} className="rounded border border-sky-500/30 bg-sky-500/10 px-4 py-2 text-xs text-sky-300 disabled:opacity-40">{backtest.running ? 'Running…' : 'Run Backtest on Loaded Data'}</button></div><p className="mt-4 text-xs text-slate-500">Uses the currently loaded backend candle and strategy sequences. React validates alignment only; calculations remain in FastAPI.</p>{backtest.error && <div className="mt-4 rounded border border-amber-500/30 bg-amber-500/10 p-3 text-xs text-amber-200">{backtest.error}</div>}{backtest.result ? <div className="mt-5 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Final equity',money(backtest.result.final_equity)],['Net profit',money(backtest.result.net_profit)],['Return',`${number(backtest.result.total_return_pct)}%`],['Trades',String(backtest.result.total_trades)],['Win rate',`${number(backtest.result.win_rate_pct)}%`],['Profit factor',number(backtest.result.profit_factor)],['Max drawdown',`${number(backtest.result.max_drawdown_pct)}%`],['Expected value',money(backtest.result.expected_value)]].map(([key,value]) => <div className="panel-soft rounded p-3" key={key}><div className="mono text-[9px] text-slate-500">{key}</div><div className="mt-2 font-semibold text-white">{value}</div></div>)}</div> : <div className="mt-5 text-xs text-slate-500">NOT RUN · No result is fabricated before explicit evaluation.</div>}</div>
}

export function TradeJournalView({ paper }: { paper: PaperViewState }) {
  const trades = paper.account?.closed_trades ?? []
  return <div className="panel rounded-lg p-5"><div className="mono text-[9px] text-slate-500">BACKEND PAPER CLOSED TRADES</div><h2 className="mt-1 text-lg font-semibold text-white">Trade Journal</h2>{trades.length ? <div className="mt-5 overflow-x-auto"><table className="w-full text-xs"><thead className="mono text-[9px] text-slate-500"><tr>{['SYMBOL','ENTRY','EXIT','NET P/L','RETURN'].map(x => <th className="px-3 py-3 text-left" key={x}>{x}</th>)}</tr></thead><tbody>{trades.slice().reverse().map((trade,index) => <tr className="border-t border-slate-800" key={`${trade.entry_timestamp}-${index}`}><td className="px-3 py-3">{trade.symbol}</td><td className="px-3 py-3">{money(trade.entry_price)}</td><td className="px-3 py-3">{money(trade.exit_price)}</td><td className="px-3 py-3">{money(trade.net_pnl)}</td><td className="px-3 py-3">{number(trade.return_pct)}%</td></tr>)}</tbody></table></div> : <div className="mt-5 text-xs text-slate-500">{paper.loading ? 'Loading…' : 'No authoritative closed paper trades available.'}</div>}</div>
}

export function SettingsView({ selection }: { selection: Selection }) {
  const real = selection.source === 'binance'
  return <div className="grid gap-4 lg:grid-cols-2"><div className="panel rounded-lg p-5"><div className="mono text-[9px] text-slate-500">RUNTIME</div><div className="mt-4 space-y-3 text-xs text-slate-400"><div>API base URL: <span className="mono text-slate-200">{API_BASE_URL}</span></div><div>Market source: <span className="text-slate-200">{real ? 'Binance Public REST' : 'Deterministic Mock'}</span></div><div>Symbol: <span className="text-slate-200">{selection.symbol}</span></div><div>Timeframe: <span className="text-slate-200">{selection.timeframe}</span></div></div></div><div className="panel rounded-lg p-5"><div className="mono text-[9px] text-slate-500">SAFETY</div><div className="mt-4 space-y-3 text-xs text-slate-400"><p>No broker credentials are configured in this UI.</p><p>No live-order control is exposed.</p><p>Real market failure never silently falls back to mock.</p><p>RiskContext remains fail-closed when incomplete.</p></div></div></div>
}
