import { Activity, RefreshCw, WalletCards } from 'lucide-react'
import type { Candle, IndicatorSnapshot, StrategyResult } from '../api/types'
import type { PaperViewState, Selection } from './DashboardViews'
import { TrafficLightStatus, type TrafficLightTone } from './TrafficLightStatus'

const NA='N/A'
const number=(value:number|null|undefined,digits=2)=>value==null?NA:value.toFixed(digits)
const usdt=(value:number|null|undefined)=>value==null?NA:`${value.toLocaleString(undefined,{maximumFractionDigits:2})} USDT`
const assessment=(value:string|null|undefined)=>value?.replace(/_/g,' ')??NA
const bullish=(strategy?:StrategyResult)=>Boolean(strategy?.data_ready&&(strategy.assessment==='BULLISH'||strategy.assessment==='STRONG_BULLISH'))
function marketTraffic(strategy?:StrategyResult):{tone:TrafficLightTone;label:string;detail:string}{if(!strategy?.data_ready)return{tone:'yellow',label:'TUNGGU DATA',detail:'Data Strategy belum lengkap. Jangan membuat keputusan entry.'};if(strategy.assessment==='STRONG_BEARISH')return{tone:'red',label:'JANGAN BUY',detail:'Kondisi STRONG BEARISH. Entry long baru ditahan.'};if(strategy.assessment==='BEARISH')return{tone:'red',label:'TUNGGU · BEARISH',detail:'Tekanan pasar masih bearish. Tunggu perubahan kondisi.'};if(strategy.assessment==='NEUTRAL')return{tone:'yellow',label:'TUNGGU KONFIRMASI',detail:'Pasar netral. Belum ada arah bullish yang cukup untuk calon BUY.'};if(strategy.assessment==='BULLISH')return{tone:'yellow',label:'CALON ENTRY · EVALUASI RISIKO',detail:'Strategy bullish, tetapi Risk Guard belum memberi izin transaksi.'};if(strategy.assessment==='STRONG_BULLISH')return{tone:'yellow',label:'SETUP KUAT · EVALUASI RISIKO',detail:'Strategy strong bullish. Tetap wajib lolos Risk Sizing dan Risk Guard.'};return{tone:'yellow',label:'TUNGGU',detail:'Belum ada kondisi entry yang dapat dievaluasi.'}}

export function DashboardIndonesia({selection,candle,indicator,strategy}:{selection:Selection;candle?:Candle;indicator?:IndicatorSnapshot;strategy?:StrategyResult;loading:boolean}){
 const traffic=marketTraffic(strategy)
 return <><section className="mb-5 grid gap-4 md:grid-cols-3"><div className="panel rounded-lg p-5"><div className="mono text-[9px] font-semibold text-sky-300">HARGA PASAR TERAKHIR</div><div className="mt-3 text-4xl font-bold text-white">{candle?`$${candle.close.toLocaleString(undefined,{maximumFractionDigits:2})}`:NA}</div><div className="mt-2 text-sm text-slate-300">{candle?.symbol??selection.symbol} · {candle?.timeframe??selection.timeframe}</div><div className="mt-1 mono text-[9px] text-slate-500">{candle?new Date(candle.timestamp).toLocaleString('id-ID'):NA}</div></div><div className="panel rounded-lg p-5"><div className="mono text-[9px] font-semibold text-sky-300">KONDISI PASAR · STRATEGY ENGINE</div><div className="mt-3 text-3xl font-bold text-white">{assessment(strategy?.assessment)}</div><div className="mt-2 text-sm text-slate-300">Skor {strategy?.score??NA} · Normalisasi {strategy?.normalized_score??NA}%</div><div className="mt-4 text-xs text-slate-300">Kondisi pasar bukan izin eksekusi.</div></div><div className="panel rounded-lg p-4"><div className="mono mb-3 text-[9px] font-semibold text-sky-300">STATUS ENTRY · TRAFFIC LIGHT</div><TrafficLightStatus {...traffic}/></div></section><section className="panel mb-5 rounded-lg p-5"><div className="mb-5 flex items-center justify-between"><div><div className="mono text-[9px] font-semibold text-sky-300">MESIN TEKNIKAL</div><h2 className="mt-1 font-semibold text-white">EMA · RSI · MACD</h2></div><Activity size={18} className="text-sky-300"/></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-6">{[['EMA FAST',indicator?.ema_fast],['EMA SLOW',indicator?.ema_slow],['RSI',indicator?.rsi],['MACD',indicator?.macd],['SIGNAL',indicator?.macd_signal],['HISTOGRAM',indicator?.macd_histogram]].map(([name,value])=><div className="panel-soft rounded p-3" key={String(name)}><div className="mono text-[9px] font-semibold text-sky-300">{name}</div><div className="mt-2 font-bold text-white">{number(value as number|null|undefined,4)}</div></div>)}</div></section><section className="panel rounded-lg p-5"><div className="mono text-[9px] font-semibold text-sky-300">STATUS SISTEM</div><div className="mt-4 grid gap-3 md:grid-cols-4"><TrafficLightStatus compact tone="green" label="DATA REAL" detail="Input observasi aktif."/><TrafficLightStatus compact tone="green" label="BACKEND AKTIF" detail="Keputusan tetap di backend."/><TrafficLightStatus compact tone="yellow" label="PAPER TRADING" detail="Simulasi, bukan dana nyata."/><TrafficLightStatus compact tone="red" label="UANG NYATA NONAKTIF" detail="Tanpa eksekusi broker."/></div></section></>
}

export function RiskGuardIndonesia({strategy}:{strategy?:StrategyResult}){
 const traffic=marketTraffic(strategy),eligible=bullish(strategy)
 return <div className="panel rounded-lg p-6"><div className="mono text-[9px] font-semibold text-sky-300">GERBANG RISIKO OTORITATIF</div><div className="mt-4 max-w-2xl"><TrafficLightStatus tone={eligible?'yellow':traffic.tone} label={eligible?'BELUM ADA IZIN ENTRY':traffic.label} detail={eligible?'Strategy memenuhi syarat awal, tetapi proposal BUY belum lolos Risk Guard. Masukkan Stop Loss dan batas risiko untuk evaluasi backend.':traffic.detail}/></div><p className="mt-4 max-w-3xl text-sm leading-6 text-slate-200">{eligible?'TradingGuard baru membentuk RiskContext lengkap setelah Stop Loss dan batas risiko diberikan. Risk Guard kemudian memutuskan DIIZINKAN, PERINGATAN, atau DITOLAK.':'Entry tetap fail-closed. Status pasar tidak pernah otomatis menjadi izin transaksi.'}</p><div className="mt-5 panel-soft rounded p-4 text-xs text-slate-300">Kondisi pasar: <span className="font-bold text-white">{assessment(strategy?.assessment)}</span> · Izin entry: <span className="font-bold text-amber-200">BELUM ADA</span></div></div>
}

export function PaperTradingIndonesia({paper}:{paper:PaperViewState}){
 const a=paper.account,p=paper.performance,started=Boolean(a?.active),realizedPnl=started&&a?a.realized_equity-a.initial_capital:null
 const reset=async()=>{if(window.confirm('Reset akun virtual PAPER ke 10.000 USDT? Posisi terbuka, aksi tertunda, dan riwayat PAPER akan dihapus.'))await paper.reset()}
 const paperStatus:TrafficLightTone=!started?'red':a?.open_position?'green':a?.pending_entry?'yellow':'yellow'
 const paperLabel=!started?'PAPER NONAKTIF':a?.open_position?'POSISI PAPER AKTIF':a?.pending_entry?'BUY MENUNGGU REVALIDASI':'PAPER AKTIF · MENUNGGU SETUP'
 const paperDetail=!started?'Mulai akun virtual sebelum evaluasi entry.':a?.open_position?'Posisi virtual sedang terbuka. Stop-loss dan exit tetap dikelola backend.':a?.pending_entry?'Proposal BUY sudah dijadwalkan, tetapi harga OPEN berikutnya wajib lolos Risk Guard lagi.':'Saldo virtual aktif. Belum ada posisi atau BUY yang dijadwalkan.'
 return <div className="space-y-4"><div className="panel rounded-lg p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="mono text-[9px] font-semibold text-sky-300">AKUN VIRTUAL · PAPER ONLY</div><div className="mt-2 flex items-center gap-2 text-2xl font-bold text-white"><WalletCards className="text-sky-300"/>{paper.loading?'MEMUAT…':started?'PAPER AKTIF':'BELUM DIMULAI'}</div><div className="mt-2 text-xs text-slate-300">Mata uang: USDT · Saldo awal: 10.000 USDT · Bukan dana nyata</div></div><div className="flex gap-2">{!started&&<button disabled={paper.loading||paper.mutating} onClick={()=>void paper.start()} className="rounded border border-sky-500/30 bg-sky-500/10 px-4 py-2 text-xs font-semibold text-sky-200 disabled:opacity-40">{paper.mutating?'Memulai…':'Mulai Akun Paper'}</button>}<button disabled={paper.loading||paper.mutating} onClick={()=>void paper.refresh()} className="rounded border border-slate-600 px-3 py-2 text-xs text-slate-200 disabled:opacity-40"><RefreshCw size={14}/></button>{started&&<button disabled={paper.mutating} onClick={()=>void reset()} className="rounded border border-amber-500/30 bg-amber-500/10 px-4 py-2 text-xs text-amber-200 disabled:opacity-40">Reset Akun Virtual</button>}</div></div><div className="mt-5"><TrafficLightStatus tone={paperStatus} label={paperLabel} detail={paperDetail}/></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['SALDO TERSEDIA',usdt(started?a?.cash:null)],['EKUITAS TEREALISASI',usdt(started?a?.realized_equity:null)],['P/L TEREALISASI',usdt(realizedPnl)],['TOTAL BIAYA',usdt(started?a?.total_transaction_cost:null)]].map(([label,value])=><div className="panel rounded-lg p-4" key={label}><div className="mono text-[9px] font-semibold text-sky-300">{label}</div><div className="mt-2 text-xl font-bold text-white">{value}</div></div>)}</div><div className="grid gap-4 lg:grid-cols-2"><div className="panel rounded-lg p-5"><div className="mono text-[9px] font-semibold text-sky-300">STATUS POSISI</div><div className="mt-4 text-lg font-semibold text-white">{started?(a?.open_position?`${a.open_position.symbol} · POSISI TERBUKA`:'TIDAK ADA POSISI TERBUKA'):'N/A'}</div><div className="mt-3 text-xs text-slate-300">Trade selesai: {started?(p?.total_closed_trades??a?.closed_trades.length??NA):NA} · Win rate: {started&&p?`${number(p.win_rate_pct)}%`:NA}</div></div><div className="panel rounded-lg p-5"><div className="mono text-[9px] font-semibold text-sky-300">KEAMANAN EKSEKUSI</div><p className="mt-4 text-xs leading-6 text-slate-200">Mengaktifkan akun virtual hanya membuat saldo PAPER. Entry baru hanya dapat dijadwalkan setelah Risk Sizing dan Risk Guard mengizinkan; harga OPEN berikutnya tetap wajib lolos pemeriksaan ulang.</p></div></div></div>
}
