import { useState } from 'react'
import { tradingGuardApi, type ManualTradeResult, type MarketSource } from '../api/client'
import type { StrategyResult } from '../api/types'
import type { PaperViewState } from './DashboardViews'
import { TrafficLightStatus, type TrafficLightTone } from './TrafficLightStatus'

function tone(result:ManualTradeResult|null):TrafficLightTone{if(!result)return'yellow';if(result.executed)return'green';return result.decision==='BLOCK'?'red':'yellow'}

export function ManualTradeControl({paper,strategy,source='binance'}:{paper:PaperViewState;strategy?:StrategyResult;source?:MarketSource}){
  const [busy,setBusy]=useState(false),[result,setResult]=useState<ManualTradeResult|null>(null),[error,setError]=useState<string|null>(null)
  const [riskBudget,setRiskBudget]=useState('0.5'),[maxAllocation,setMaxAllocation]=useState('20')
  const active=Boolean(paper.account?.active),symbol=strategy?.symbol,position=symbol?paper.account?.open_positions?.find(item=>item.symbol===symbol):undefined,hasPosition=Boolean(position)
  const buy=async()=>{if(!strategy||busy)return;const rb=Number(riskBudget),ma=Number(maxAllocation);if(!Number.isFinite(rb)||rb<=0||rb>1){setError('Risk budget harus > 0% dan maksimal 1%.');return}if(!Number.isFinite(ma)||ma<=0||ma>100){setError('Maks. alokasi harus > 0% dan maksimal 100%.');return}setBusy(true);setError(null);try{const r=await tradingGuardApi.manualPaperBuy(strategy.symbol,strategy.timeframe,source,rb,ma);setResult(r);await paper.refresh()}catch(e){setError(e instanceof Error?e.message:'Manual BUY gagal.')}finally{setBusy(false)}}
  const sell=async()=>{if(busy||!symbol)return;setBusy(true);setError(null);try{const r=await tradingGuardApi.manualPaperSell(symbol,source);setResult(r);await paper.refresh()}catch(e){setError(e instanceof Error?e.message:'Manual SELL gagal.')}finally{setBusy(false)}}
  return <div className="panel rounded-lg p-5"><div className="mono text-[9px] font-semibold text-sky-300">MANUAL + GUARD · PAPER ONLY</div><h2 className="mt-1 text-lg font-semibold text-white">Uji Keputusan BUY / SELL · {symbol??'N/A'}</h2><p className="mt-2 text-xs leading-5 text-slate-300">Setiap symbol memiliki posisi sendiri. BUY tetap wajib Auto Stop → Risk Sizing → Risk Guard. Risk Guard membaca exposure gabungan seluruh portfolio. SELL hanya menutup symbol yang sedang dipilih.</p><div className="mt-4 grid gap-3 md:grid-cols-4"><div className="panel-soft rounded p-3"><div className="mono text-[9px] text-slate-500">KONDISI PASAR</div><div className="mt-1 font-bold text-white">{strategy?.assessment??'N/A'}</div></div><label className="text-xs text-slate-300">Risk budget (%)<input value={riskBudget} onChange={e=>setRiskBudget(e.target.value)} className="mt-1 w-full rounded px-3 py-2"/></label><label className="text-xs text-slate-300">Maks. alokasi (%)<input value={maxAllocation} onChange={e=>setMaxAllocation(e.target.value)} className="mt-1 w-full rounded px-3 py-2"/></label><div className="panel-soft rounded p-3"><div className="mono text-[9px] text-slate-500">POSISI {symbol??''}</div><div className="mt-1 font-bold text-white">{hasPosition?'TERBUKA':'FLAT'}</div></div></div><div className="mt-4 flex gap-3"><button disabled={!active||hasPosition||!strategy||busy} onClick={()=>void buy()} className="rounded border border-emerald-400/40 bg-emerald-500/15 px-6 py-2.5 text-sm font-bold text-emerald-200 disabled:opacity-35">BUY + RISK GUARD</button><button disabled={!active||!hasPosition||busy} onClick={()=>void sell()} className="rounded border border-red-400/40 bg-red-500/15 px-6 py-2.5 text-sm font-bold text-red-200 disabled:opacity-35">SELL / CLOSE {symbol??''}</button></div>{result&&<div className="mt-4"><TrafficLightStatus tone={tone(result)} label={result.executed?`${result.action} PAPER DIEKSEKUSI`:`${result.action} DITOLAK · ${result.decision}`} detail={result.reason}/></div>}{error&&<div className="mt-4 rounded border border-red-500/40 bg-red-500/10 p-3 text-xs text-red-200">{error}</div>}</div>
}
