import { WalletCards } from 'lucide-react'
import type { PaperPosition } from '../api/types'
import type { PaperViewState } from './DashboardViews'

const money=(value:number)=>`${value.toLocaleString(undefined,{minimumFractionDigits:2,maximumFractionDigits:2})} USDT`
export type PaperMarks=Record<string,number>

function PositionCard({position,mark,selected}:{position:PaperPosition;mark?:number;selected:boolean}){
 const pnl=mark==null?null:(mark-position.entry_price)*position.quantity
 const pct=pnl==null?null:(pnl/(position.entry_notional+position.entry_transaction_cost))*100
 const tone=pnl==null?'text-slate-400':pnl>=0?'text-emerald-300':'text-red-300'
 return <div className={`panel-soft rounded-lg border p-4 ${selected?'border-sky-400/50':'border-slate-700'}`}><div className="flex items-center justify-between"><div className="font-bold text-white">{position.symbol}</div><div className="mono text-[9px] text-slate-500">{selected?'SYMBOL DIPILIH':'OPEN'}</div></div><div className="mt-3 grid grid-cols-2 gap-2 text-xs text-slate-300"><div>Entry<br/><b className="text-white">{position.entry_price.toLocaleString()}</b></div><div>Harga kini<br/><b className="text-white">{mark==null?'Memuat…':mark.toLocaleString()}</b></div><div>Qty<br/><b className="text-white">{position.quantity.toFixed(6)}</b></div><div>Stop Loss<br/><b className="text-white">{position.stop_loss_price?.toLocaleString()??'—'}</b></div></div><div className={`mt-4 text-lg font-bold ${tone}`}>{pnl==null?'P/L —':`${pnl>=0?'+':''}${money(pnl)} · ${pct!>=0?'+':''}${pct!.toFixed(2)}%`}</div></div>
}

export function PortfolioPaperView({paper,selectedSymbol,marks}:{paper:PaperViewState;selectedSymbol:string;marks:PaperMarks}){
 const a=paper.account,p=paper.performance,started=Boolean(a?.active),positions=a?.open_positions??[],selected=positions.find(x=>x.symbol===selectedSymbol)
 const floating=positions.reduce((sum,pos)=>{const mark=marks[pos.symbol];return mark==null?sum:sum+(mark-pos.entry_price)*pos.quantity},0)
 const markedValue=positions.reduce((sum,pos)=>{const mark=marks[pos.symbol];return sum+(mark==null?pos.entry_notional:mark*pos.quantity)},0)
 const totalEquity=started&&a?a.cash+markedValue:null
 const reset=async()=>{if(window.confirm('Reset akun virtual PAPER? Seluruh posisi, histori, dan state persisten akan dihapus.'))await paper.reset()}
 return <div className="space-y-4"><div className="panel rounded-lg p-5"><div className="flex flex-wrap items-center justify-between gap-4"><div><div className="mono text-[9px] font-semibold text-sky-300">PORTFOLIO VIRTUAL · PAPER ONLY · SQLITE PERSISTENT</div><div className="mt-2 flex items-center gap-2 text-2xl font-bold text-white"><WalletCards className="text-sky-300"/>{started?'PAPER AKTIF':'BELUM DIMULAI'}</div><div className="mt-2 text-xs text-slate-300">{positions.length} posisi terbuka · data Paper disimpan lokal dan dipulihkan setelah backend restart.</div></div><div className="flex gap-2">{!started&&<button disabled={paper.loading||paper.mutating} onClick={()=>void paper.start()} className="rounded border border-sky-500/30 bg-sky-500/10 px-4 py-2 text-xs font-semibold text-sky-200">Mulai Akun Paper</button>}{started&&<button disabled={paper.mutating} onClick={()=>void reset()} className="rounded border border-amber-500/30 bg-amber-500/10 px-4 py-2 text-xs text-amber-200">Reset Akun Virtual</button>}</div></div></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{[['SALDO TERSEDIA',started&&a?money(a.cash):'N/A'],['TOTAL EQUITY',totalEquity==null?'N/A':money(totalEquity)],['FLOATING P/L',started?`${floating>=0?'+':''}${money(floating)}`:'N/A'],['REALIZED P/L',started&&a?money(a.realized_equity-a.initial_capital):'N/A']].map(([k,v])=><div className="panel rounded-lg p-4" key={k}><div className="mono text-[9px] font-semibold text-sky-300">{k}</div><div className="mt-2 text-xl font-bold text-white">{v}</div></div>)}</div><div className="panel rounded-lg p-5"><div className="mono text-[9px] font-semibold text-sky-300">SYMBOL DIPILIH · {selectedSymbol}</div><div className="mt-3 text-lg font-bold text-white">{selected?`${selectedSymbol} · POSISI TERBUKA`:`${selectedSymbol} · TIDAK ADA POSISI`}</div><div className="mt-2 text-xs text-slate-300">Pindah symbol tidak mengubah posisi lain. BUY/SELL hanya bekerja pada symbol yang sedang dipilih.</div></div><div><div className="mono mb-3 text-[9px] font-semibold text-sky-300">OPEN POSITIONS · PORTFOLIO</div>{positions.length?<div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{positions.map(pos=><PositionCard key={pos.symbol} position={pos} mark={marks[pos.symbol]} selected={pos.symbol===selectedSymbol}/>)}</div>:<div className="panel rounded-lg p-5 text-sm text-slate-400">Belum ada posisi PAPER terbuka.</div>}</div><div className="panel rounded-lg p-4 text-xs text-slate-300">Trade selesai: {p?.total_closed_trades??a?.closed_trades.length??0} · Win rate: {p&&p.total_closed_trades>0?`${p.win_rate_pct.toFixed(2)}%`:'—'} · Total biaya: {a?money(a.total_transaction_cost):'N/A'}</div></div>
}
