import type{AutoPaperCycleResult,BacktestEvaluateRequest,BacktestResult,Candle,HealthResponse,IndicatorSnapshot,PaperAccount,PaperPerformanceSnapshot,PaperProcessRequest,PaperStartRequest,RiskEvaluateRequest,RiskResult,StrategyResult}from'./types'
export type MarketSource='mock'|'binance'
const API_BASE_URL=(import.meta.env.VITE_API_URL||'http://localhost:8000').replace(/\/+$/,'')
async function request<T>(path:string,init?:RequestInit):Promise<T>{const response=await fetch(`${API_BASE_URL}${path}`,{...init,headers:{Accept:'application/json',...init?.headers}});if(!response.ok){let detail=`${response.status} ${response.statusText}`;try{const body=(await response.json())as{detail?:string};if(body.detail)detail=body.detail}catch{/* preserve */}throw new Error(detail)}return response.json()as Promise<T>}
function query(path:string,params:Record<string,string|number>):string{const s=new URLSearchParams();Object.entries(params).forEach(([k,v])=>s.set(k,String(v)));return`${path}?${s.toString()}`}
function post():RequestInit{return{method:'POST',headers:{'Content-Type':'application/json'}}}
function json(body:unknown):RequestInit{return{...post(),body:JSON.stringify(body)}}
export const tradingGuardApi={getHealth:()=>request<HealthResponse>('/health'),getMarketCandles:(symbol:string,timeframe:string,limit=100,source:MarketSource='mock')=>request<Candle[]>(query('/market/candles',{symbol,timeframe,limit,source})),getIndicators:(symbol:string,timeframe:string,limit=100,source:MarketSource='mock')=>request<IndicatorSnapshot[]>(query('/indicators',{symbol,timeframe,limit,source})),getStrategy:(symbol:string,timeframe:string,limit=100,source:MarketSource='mock')=>request<StrategyResult[]>(query('/strategy',{symbol,timeframe,limit,source})),evaluateRisk:(payload:RiskEvaluateRequest)=>request<RiskResult>('/risk/evaluate',json(payload)),startPaper:(payload:PaperStartRequest={})=>request<PaperAccount>('/paper/start',json(payload)),autoPaperCycle:(symbol:string,timeframe:string,source:MarketSource='binance',riskBudget=0.5,maxAllocation=20)=>request<AutoPaperCycleResult>(query('/paper/auto-cycle',{symbol,timeframe,source,risk_budget_pct:riskBudget,max_allocation_pct:maxAllocation}),post()),processPaper:(payload:PaperProcessRequest)=>request<PaperAccount>('/paper/process',json(payload)),getPaperState:()=>request<PaperAccount>('/paper/state'),getPaperPerformance:()=>request<PaperPerformanceSnapshot>('/paper/performance'),resetPaper:()=>request<PaperAccount>('/paper/reset',json({})),evaluateBacktest:(payload:BacktestEvaluateRequest)=>request<BacktestResult>('/backtest/evaluate',json(payload))}
export{API_BASE_URL}
